#!/system/bin/sh

busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

busybox rm -f $LS
busybox touch $LS

busybox echo "1024" > /proc/sys/kernel/random/read_wakeup_threshold
busybox echo "2048" > /proc/sys/kernel/random/write_wakeup_threshold

busybox sleep 1
