#!/system/bin/sh

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system


busybox sleep 10

	busybox killall -9 android.process.media
	busybox killall -9 mediaserver
  busybox killall -9 com.google.android.gms
  busyboxkillall -9 com.google.android.gsf
